version: '3.4'

services:
  backendcovid19reservationapp:
    image: backendcovid19reservationapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/server.js"]
  database:
    image: mysql:5.7
    ports:
        - "3306:3306"
    volumes:
        - /var/lib/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: reservation_app
        MYSQL_USER: backend
        MYSQL_PASSWORD: 1234
        MYSQL_ROOT_HOST: '%'
  